### PR TITLE
Added badges: build status, coverage, license, pypi

### PR DESCRIPTION
**Pull request by aliev**

### CODE REVIEW

**Comment by aliev** [comment]
@synchronizing I think it will be useful and revive the README a little. What do you think? :) That's how it looks like: https://github.com/aliev/aioauth/blob/feature/readme-badges/README.md

**Comment by synchronizing** [comment]
I like this! A few suggestions I've done in my own personal repos that I personally thinks adds some flavors:

---

Finding an emoji for the entire project is usually enough to give it color and make the README clean. Take this (my own project, but just as an example):

Screen Shot 2021-02-26 at 1 03 04 PM

Something like 🔐 .

---

You can center the badges by using HTML. This is an example for the 'Toolbox' project above:

```html
<p align="center">

  <a href="https://github.com/synchronizing/toolbox/actions?query=workflow%3ABuild">
    <img src="https://github.com/synchronizing/toolbox/workflows/Build/badge.svg?branch=master&event=push">
  </a>

<a href="https://synchronizing.github.io/toolbox/">
    <img src="https://github.com/synchronizing/toolbox/workflows/Docs/badge.svg?branch=master&event=push">
  </a>

  <a href="https://coveralls.io/github/synchronizing/toolbox?branch=master">
    <img src="https://coveralls.io/repos/github/synchronizing/toolbox/badge.svg?branch=master">
  </a>

  <a href="https://opensource.org/licenses/MIT">
    <img src="https://img.shields.io/badge/License-MIT-yellow.svg">
  </a>
</p>
```

---

If we rename this to "Build" we will have a more clear output on the Github badge (like the example above).

https://github.com/aliev/aioauth/blob/0d790dffc020027057002724599f507ae8096274/.github/workflows/python-package.yml#L4

**Comment by aliev** [comment]
@synchronizing look great, I like it!

> If we rename this to "Build" we will have a more clear output on the Github badge (like the example above).

very good point!

**Comment by synchronizing** [comment]
Side note: Planning on updating `README.md` on #21. Will leave it for last commit and you can check it out and give any feedback.

**Pull request merged**
