### PR TITLE
Implement token revocation endpoint

### PR DESCRIPTION
**Pull request by mgorven**
RFC 7009: OAuth 2.0 Token Revocation
https://datatracker.ietf.org/doc/html/rfc7009

### CODE REVIEW

**Review by aliev — APPROVED** [review]
Thank you approved!

**Comment by shawn-monadical** [comment]
Hi there @aliev, it seems like this didn't get included in the most recent release v1.5.4, was that intentional? Do you know when this feature might get released? Thanks, Shawn

**Comment by aliev** [comment]
Hi, @shawn-monadical 

Sorry for the late reply; I had a tough week. Give me some time after the weekend, and I will review all possible options regarding the release. I’ll also try to answer your questions in Discussions.

**Comment by shawn-monadical** [comment]
No worries @aliev, hope you're feeling better and of course thank you for your work on this excellent project. It's been a big help for me.

**Comment by aliev** [comment]
@shawn-monadical I released v1.6.0. Could you check, please?

**Comment by shawn-monadical** [comment]
Thanks @aliev, it seems the token revocation endpoint and the new OIDC classes are included in the latest release, exactly what I needed!

**Pull request merged**
