### PR TITLE
minimum viable fastapi aioauth example

### PR DESCRIPTION
**Pull request by imgurbot12**
created based on discussion in https://github.com/aliev/aioauth/pull/106

### CODE REVIEW

**Comment by aliev** [comment]
Thanks!

I have a few ideas if you don’t mind.

**Ability to load fixtures and configuration during startup**

To facilitate the process of setting up the model's data (clients, users, etc), we could provide the configuration file support. The configuration file might look like this:

```bash
cat config.json
```

```json
{
    "fixtures": {
        "users": {"id": "...", "username": "...", ...},
        "clients": {...},
        ...
    },
    "settings": {"INSECURE_TRANSPORT": true, ...}
}
```

(I was thinking about yaml, but I think it requires additional dependency)

this way `fixtures` will be automatically loaded into the memory database before the server starts.

```
python -m examples/fastapi_example.py # Loads the config.json fixture from the current directory
```

**Making package out of the examples**

I suggest creating a python package in `examples` with a `pyproject.toml` file for now. The directory and file structure would look like this:

```
examples/fastapi/__init__.py
examples/fastapi/__main__.py
examples/fastapi/pyproject.toml
...
```

**Making sure that formatting is consistent**

Could you apply `pre-commit` and check if there are any formatting fixes needed? Just run the command: `pre-commit run --all-files`

**Comment by imgurbot12** [comment]
Hey @aliev, happy to follow with what you've posted but I have a few questions about it.

First is, naming the folder `fastapi` and making it a module will unfortunately put it first in the import path meaning i wouldn't actually be able to import the real `fastapi` library since it will try to load from the local folder and fail to import anything. I had that issue with just naming the script `fastapi.py` which is why i renamed it to `fastapi_example`. Whats a good alternative for the name do you think?

Second, this is more of a design decision but at the moment I made store its own library with `fastapi_example.py ` just being a script since I thought other examples using other async frameworks like [sanic](https://github.com/sanic-org/sanic) could re-use the database models and storage-backends.

Is that valuable at all or would you just prefer it all to be a self-contained example for just fastapi?

**Comment by aliev** [comment]
> Hey @aliev, happy to follow with what you've posted but I have a few questions about it.
> 
> First is, naming the folder `fastapi` and making it a module will unfortunately put it first in the import path meaning i wouldn't actually be able to import the real `fastapi` library since it will try to load from the local folder and fail to import anything. I had that issue with just naming the script `fastapi.py` which is why i renamed it to `fastapi_example`. Whats a good alternative for the name do you think?

Ah yes, of course, you are right. I just meant to say earlier that the example for FastAPI should be presented as a package. However, the package name "FastAPI" itself might cause issues. Sorry, I should have been more precise.

> Second, this is more of a design decision but at the moment I made store its own library with `fastapi_example.py ` just being a script since I thought other examples using other async frameworks like [sanic](https://github.com/sanic-org/sanic) could re-use the database models and storage-backends.
> 
> Is that valuable at all or would you just prefer it all to be a self-contained example for just fastapi?

I was thinking of something like this:

```
(.venv) ➜  aioauth git:(release/2.0.0) ✗ ls examples 
fastapi        pyproject.toml sanic          shared
(.venv) ➜  aioauth git:(release/2.0.0) ✗ ls examples/fastapi 
__init__.py __main__.py __pycache__ server.py
(.venv) ➜  aioauth git:(release/2.0.0) ✗ cat examples/fastapi/server.py 
from examples.shared.models import BaseModel
from fastapi import FastAPI

app = FastAPI()
(.venv) ➜  aioauth git:(release/2.0.0) ✗ cat examples/fastapi/__main__.py 
import uvicorn

if __name__ == "__main__":
    uvicorn.run(
        "examples.fastapi.server:app",
    )%                                                                                                                            (.venv) ➜  aioauth git:(release/2.0.0) ✗ python -m examples.fastapi   
INFO:     Started server process [15204]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
```

Indeed, having a module name that matches the name of the installed package can sometimes cause issues. Perhaps it's best not to complicate things here and keep `fastapi_example.py`.

Besides that, It would be very convenient to have `pyproject.toml` inside the `examples` directory, with different requirement sections for various examples.

**Comment by imgurbot12** [comment]
alright, just updated the codebase based on the directory structure you recommend.

Unfortunately, due to the new directory structure, I had to use of [sys.path inserts](https://github.com/aliev/aioauth/pull/107/commits/71f8d6af40e9f174c5031f7516ff7f482fdfc77e#diff-fe70c3d6a1b9354897bc94f67d60484a1fbe5c4f92e1284dd63327c3e7529545R7-R16) to get the scripts to be able to reference the shared library, but mypy and flake8 dont seem to like that:

```
mypy:
examples/fastapi/example.py:27: error: Cannot find implementation or library stub for module named "shared"  [import-not-found]
flake8:
examples/fastapi/example.py:17:1: E402 module level import not at top of file
```

Are you trying to convert the examples into more of a library? I suppose we could do that but I would politely push back on that a little bit and say I think the examples are simpler and easier to follow when they act like scripts rather than something to be imported. I would imagine most people using this library will be making their own oauth-services that will function standalone rather than a library so I think this format makes it cleaner and easier to understand, assuming we can fix the linter issues.

**Comment by aliev** [comment]
> alright, just updated the codebase based on the directory structure you recommend.
> 
> Unfortunately, due to the new directory structure, I had to use of [sys.path inserts](https://github.com/aliev/aioauth/pull/107/commits/71f8d6af40e9f174c5031f7516ff7f482fdfc77e#diff-fe70c3d6a1b9354897bc94f67d60484a1fbe5c4f92e1284dd63327c3e7529545R7-R16) to get the scripts to be able to reference the shared library, but mypy and flake8 dont seem to like that:
> 
> ```
> mypy:
> examples/fastapi/example.py:27: error: Cannot find implementation or library stub for module named "shared"  [import-not-found]
> flake8:
> examples/fastapi/example.py:17:1: E402 module level import not at top of file
> ```
> 
> Another issue is the `pyproject.toml` does not know how to handle two folders containing python code in the same structure and causes it to error if you try and do an install or something.
> 
> Are you trying to convert the examples into more of a library? I suppose we could do that but I would politely push back on that a little bit and say I think the examples are simpler and easier to follow when they act like scripts rather than something to be imported. I would imagine most people using this library will be making their own oauth-services that will function standalone rather than a library so I think this format makes it cleaner and easier to understand, assuming we can fix the linter issues.

Yes, I agree with you. Let's keep it as simple as possible and leave it as an example.

**Comment by imgurbot12** [comment]
> Yes, I agree with you. Let's keep it as simple as possible and leave it as an example (fastapi_example instead of creating a new package).

Hey apologizes for the delay, got a bit distracted with work but I've put it back to the flat example like we talked about.
All pre-commit checks pass :)

**Review by aliev — APPROVED** [review]

**Comment by aliev** [comment]
> > Yes, I agree with you. Let's keep it as simple as possible and leave it as an example (fastapi_example instead of creating a new package).
> 
> Hey apologizes for the delay, got a bit distracted with work but I've put it back to the flat example like we talked about. All pre-commit checks pass :)

I approved it, thank you! Regarding of `pyproject.toml`, should we still keep it?

**Comment by imgurbot12** [comment]
> I approved it, thank you! Regarding of pyproject.toml, should we still keep it?

I'm not sure what value it still has since we're not making it a library so probably not? but also entirely up to you lol.

**Comment by aliev** [comment]
> > I approved it, thank you! Regarding of pyproject.toml, should we still keep it?
> 
> I'm not sure what value it still has since we're not making it a library so probably not? but also entirely up to you lol.

let's remove it from this PR, and afterwards we're good to merge it! :)

**Comment by imgurbot12** [comment]
done! :)

**Pull request merged**
