### PR TITLE
Bugfix for refresh token scope

### PR DESCRIPTION
**Pull request by danygielow**
Hi, thank you for your library.

I found a bug though. When refreshing a token the resulting scope should be 

- the scope of the previous token, if no scope was given OR
- a scope that doesn't have a bigger scope than the previous token

see https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/

### CODE REVIEW

**Comment by aliev** [comment]
@danygielow many thanks for your contribution! could you please adjust your PR, since we have flake8 errors in CI. I added more details in contributing section: https://github.com/aliev/aioauth#contributing

**Comment by danygielow** [comment]
I used pre-commit with the pre-commit-config in the project. It seems that the black or flake8 Version is not consistent between python workflows in the checks. Maybe you could use `pre-commit run -a|--all-files` for consistency. Or remove the pre-commit-config.

**Comment by aliev** [comment]
@danygielow I pinned the black version for pre-commit: https://github.com/aliev/aioauth/pull/15

**Review by aliev — APPROVED** [review]

**Comment by danygielow** [comment]
I added a test specifically for the RefreshTokenGrantType to test the handling of given scopes, because in the authorization scope test the request is tested too strictly. 
There the response has to include the exact scope as given in the request. Which doesn't apply to refresh_token.

**Review by aliev — APPROVED** [review]

**Comment by aliev** [comment]
@danygielow thank you! approved

**Comment by danygielow** [comment]
@aliev Will you release a new version with this change shortly?

**Comment by aliev** [comment]
@danygielow yes, I will release today

**Comment by aliev** [comment]
@danygielow v1.0.5 has been released

**Pull request merged**
